In [ ]:
#This case study delves into a detailed analysis of order fulfillment and delivery performance for a delivery-based business that relies on efficient
#logistics to ensure timely and accurate delivery of products to customers. The business in question operates in a highly competitive and customer-centric
#environment, where the ability to meet delivery expectations significantly influences customer satisfaction and operational efficiency.

#The dataset used in this case study contains a wide range of variables that are critical to understanding the performance of the delivery process.
#These variables include key order metrics, delivery status, city-specific delivery performance, time-to-delivery (TAT) calculations, and service-level adherence (SLA)
#metrics. Each field provides valuable insights into how the company’s delivery system performs in terms of order fulfillment, delivery timeliness, and customer satisfaction.

In [ ]:
# Business view of data provided

#Order Creation: The process begins when an order is created in the system.
#Verification: Since this is related to medicine delivery, the first step involves the verification of the prescription. The order is sent to the verification team to ensure the prescription is accurate and valid.
#Store Processing: Once the order is verified, it is forwarded to the store for fulfillment.
#Billing: After reaching the store, the order is billed and prepared for delivery.
#Rider Assignment: Once the order is billed, a rider is assigned for delivery to the customer.
#Delivery: The rider proceeds with delivering the order to the customer’s address.
#Order Cancellation: After delivery, the customer has the option to cancel the order. If the order is cancelled, the return process may begin.

In [ ]:
#What we need to do

#Track the total number of orders received, delivered, cancelled, pending, and post-delivery returns.
#Track the first TAT, second TAT, and latest TAT.
#Track the time for each leg of the process:
  #Billing time
  #Pickup time
  #Rider reach store time

In [ ]:
from google.colab import files
uploaded=files.upload()
print(uploaded)

Buffered data was truncated after reaching the output size limit.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('Sample data.csv')
df

<ipython-input-3-e485ff7de0a9>:1: DtypeWarning: Columns (36) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('Sample data.csv')

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,first_attempted,rider_reached_customer_gate,delivery_attempted,delivered,cancelled,return_pending,return_requested,firstTAT,secondTAT,latestTAT
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,NaN,16-03-2024 21:02:12,NaN,NaN,2024-03-16 22:53:00 UTC,2024-03-16 22:54:00 UTC,2024-03-16 22:54:00 UTC
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,NaN,12-03-2024 03:37:10,NaN,NaN,2024-03-12 11:45:00 UTC,2024-03-12 11:45:00 UTC,2024-03-12 11:45:00 UTC
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,NaN,26-02-2024 18:23:26,NaN,NaN,2024-02-26 20:11:00 UTC,2024-02-26 20:11:00 UTC,2024-02-26 20:11:00 UTC
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,NaN,27-02-2024 19:42:53,NaN,NaN,2024-02-27 20:49:00 UTC,2024-02-27 20:49:00 UTC,2024-02-27 21:05:00 UTC
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,NaN,02-03-2024 19:03:01,NaN,NaN,2024-03-02 19:35:00 UTC,2024-03-02 19:37:00 UTC,2024-03-02 19:37:00 UTC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,NaN,NaN,NaN,21-03-2024 09:59:00,NaN,NaN,NaN,2024-03-21 12:26:00 UTC,2024-03-21 12:26:00 UTC,2024-03-21 12:26:00 UTC
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,NaN,10-03-2024 07:38:30,NaN,10-03-2024 07:39:00,NaN,NaN,NaN,2024-03-10 13:00:00 UTC,2024-03-10 13:00:00 UTC,2024-03-10 13:00:00 UTC
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,NaN,16-03-2024 17:04:13,NaN,16-03-2024 17:04:00,NaN,NaN,NaN,2024-03-16 20:26:00 UTC,2024-03-16 20:27:00 UTC,2024-03-16 20:27:00 UTC
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,NaN,21-03-2024 15:02:43,NaN,21-03-2024 15:06:00,NaN,NaN,NaN,2024-03-21 16:48:00 UTC,2024-03-21 16:48:00 UTC,2024-03-21 16:48:00 UTC
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,NaN,09-03-2024 15:10:25,NaN,09-03-2024 15:10:00,NaN,NaN,NaN,2024-03-09 17:47:00 UTC,2024-03-09 17:47:00 UTC,2024-03-09 17:47:00 UTC

In [ ]:
#Created to track how many orders were attempted before getting delivered.
df['Order_Reattempt']=np.where(df['delivery_attempted'].notna(),1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,rider_reached_customer_gate,delivery_attempted,delivered,cancelled,return_pending,return_requested,firstTAT,secondTAT,latestTAT,Order_Reattempt
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,16-03-2024 21:02:12,NaN,NaN,2024-03-16 22:53:00 UTC,2024-03-16 22:54:00 UTC,2024-03-16 22:54:00 UTC,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,12-03-2024 03:37:10,NaN,NaN,2024-03-12 11:45:00 UTC,2024-03-12 11:45:00 UTC,2024-03-12 11:45:00 UTC,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,26-02-2024 18:23:26,NaN,NaN,2024-02-26 20:11:00 UTC,2024-02-26 20:11:00 UTC,2024-02-26 20:11:00 UTC,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,27-02-2024 19:42:53,NaN,NaN,2024-02-27 20:49:00 UTC,2024-02-27 20:49:00 UTC,2024-02-27 21:05:00 UTC,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,02-03-2024 19:03:01,NaN,NaN,2024-03-02 19:35:00 UTC,2024-03-02 19:37:00 UTC,2024-03-02 19:37:00 UTC,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,NaN,NaN,21-03-2024 09:59:00,NaN,NaN,NaN,2024-03-21 12:26:00 UTC,2024-03-21 12:26:00 UTC,2024-03-21 12:26:00 UTC,0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,10-03-2024 07:38:30,NaN,10-03-2024 07:39:00,NaN,NaN,NaN,2024-03-10 13:00:00 UTC,2024-03-10 13:00:00 UTC,2024-03-10 13:00:00 UTC,0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,16-03-2024 17:04:13,NaN,16-03-2024 17:04:00,NaN,NaN,NaN,2024-03-16 20:26:00 UTC,2024-03-16 20:27:00 UTC,2024-03-16 20:27:00 UTC,0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,21-03-2024 15:02:43,NaN,21-03-2024 15:06:00,NaN,NaN,NaN,2024-03-21 16:48:00 UTC,2024-03-21 16:48:00 UTC,2024-03-21 16:48:00 UTC,0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,09-03-2024 15:10:25,NaN,09-03-2024 15:10:00,NaN,NaN,NaN,2024-03-09 17:47:00 UTC,2024-03-09 17:47:00 UTC,2024-03-09 17:47:00 UTC,0

In [ ]:
#Created to check how many orders were delivered directly without getting cancelled after delivery
df['isDelivered']=np.where(df['LATESTORDERSTATUS']=='DELIVERED',1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,delivery_attempted,delivered,cancelled,return_pending,return_requested,firstTAT,secondTAT,latestTAT,Order_Reattempt,isDelivered
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,16-03-2024 21:02:12,NaN,NaN,2024-03-16 22:53:00 UTC,2024-03-16 22:54:00 UTC,2024-03-16 22:54:00 UTC,0,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,12-03-2024 03:37:10,NaN,NaN,2024-03-12 11:45:00 UTC,2024-03-12 11:45:00 UTC,2024-03-12 11:45:00 UTC,0,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,26-02-2024 18:23:26,NaN,NaN,2024-02-26 20:11:00 UTC,2024-02-26 20:11:00 UTC,2024-02-26 20:11:00 UTC,0,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,27-02-2024 19:42:53,NaN,NaN,2024-02-27 20:49:00 UTC,2024-02-27 20:49:00 UTC,2024-02-27 21:05:00 UTC,0,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,02-03-2024 19:03:01,NaN,NaN,2024-03-02 19:35:00 UTC,2024-03-02 19:37:00 UTC,2024-03-02 19:37:00 UTC,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,NaN,21-03-2024 09:59:00,NaN,NaN,NaN,2024-03-21 12:26:00 UTC,2024-03-21 12:26:00 UTC,2024-03-21 12:26:00 UTC,0,1
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,NaN,10-03-2024 07:39:00,NaN,NaN,NaN,2024-03-10 13:00:00 UTC,2024-03-10 13:00:00 UTC,2024-03-10 13:00:00 UTC,0,1
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,NaN,16-03-2024 17:04:00,NaN,NaN,NaN,2024-03-16 20:26:00 UTC,2024-03-16 20:27:00 UTC,2024-03-16 20:27:00 UTC,0,1
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,NaN,21-03-2024 15:06:00,NaN,NaN,NaN,2024-03-21 16:48:00 UTC,2024-03-21 16:48:00 UTC,2024-03-21 16:48:00 UTC,0,1
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,NaN,09-03-2024 15:10:00,NaN,NaN,NaN,2024-03-09 17:47:00 UTC,2024-03-09 17:47:00 UTC,2024-03-09 17:47:00 UTC,0,1

In [ ]:
# Created to track how many orders were cancelled
df['isCancelled']=np.where(df['pendencyFlag']=='cancelled',1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,pre_store_pending,postShip_Pending,DSP_Assigned,Store_Pushed,Billed_time_min,DSP_Allocation_In_Min,pickup_in_minuts,Rider_delivery_in_Min,O2D_in_min,Verified_in_Min
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,NaN,NaN,NaN,NaN,NaN,0.250000
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,1,1,3.716667,0.200000,8.466667,4.733333,26.983333,NaN
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,0,1,1,11.433333,0.183333,10.416667,3.733333,26.866667,0.266667
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,0,1,1,1.433333,5.966667,8.616667,1.733333,33.650000,NaN
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,0,1,1,58.100000,0.166667,3.783333,1.516667,16.783333,NaN
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,1,1,2.866667,0.133333,4.000000,1.483333,17.633333,NaN

In [ ]:
#Created to track orders which are pending
df['Pending']=np.where(df['pendencyFlag']=='pending',1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,pre_store_pending,postShip_Pending,DSP_Assigned,Store_Pushed,Billed_time_min,DSP_Allocation_In_Min,pickup_in_minuts,Rider_delivery_in_Min,O2D_in_min,Verified_in_Min
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,NaN,NaN,NaN,NaN,NaN,0.250000
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,1,1,3.716667,0.200000,8.466667,4.733333,26.983333,NaN
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,0,1,1,11.433333,0.183333,10.416667,3.733333,26.866667,0.266667
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,0,1,1,1.433333,5.966667,8.616667,1.733333,33.650000,NaN
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,0,1,1,58.100000,0.166667,3.783333,1.516667,16.783333,NaN
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,1,1,2.866667,0.133333,4.000000,1.483333,17.633333,NaN

In [ ]:
#Created to track the orders asking to be returned after delivery
df['Post_delivery_returns']=np.where(df['pendencyFlag']=='post-Delivery_Returns',1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,pre_store_pending,postShip_Pending,DSP_Assigned,Store_Pushed,Billed_time_min,DSP_Allocation_In_Min,pickup_in_minuts,Rider_delivery_in_Min,O2D_in_min,Verified_in_Min
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,NaN,NaN,NaN,NaN,NaN,0.250000
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,1,1,3.716667,0.200000,8.466667,4.733333,26.983333,NaN
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,0,1,1,11.433333,0.183333,10.416667,3.733333,26.866667,0.266667
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,0,1,1,1.433333,5.966667,8.616667,1.733333,33.650000,NaN
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,0,1,1,58.100000,0.166667,3.783333,1.516667,16.783333,NaN
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,1,1,2.866667,0.133333,4.000000,1.483333,17.633333,NaN

In [ ]:
#Created to track the First TAT Adherence
df['Formatted_createddate']=pd.to_datetime(df['created_ts_IST']).dt.strftime('%Y-%m-%d %H:%M:%S')
df['Formatted_createddate']=pd.to_datetime(df['Formatted_createddate'])
df['firstTAT']=pd.to_datetime(df['firstTAT']).dt.strftime('%Y-%m-%d %H:%M:%S')
df['firstTAT']=pd.to_datetime(df['firstTAT'])

<ipython-input-10-de636df41e26>:2: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Formatted_createddate']=pd.to_datetime(df['created_ts_IST']).dt.strftime('%Y-%m-%d %H:%M:%S')

In [ ]:
#Created to track the difference between First TAT and created date
df['Created_to_FTAT_Diff']=np.where(df['firstTAT'].notna() & df['Formatted_createddate'].notna(),
np.maximum((df['firstTAT'] - df['Formatted_createddate']).dt.total_seconds() / 60, 0),np.nan)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,firstTAT,secondTAT,latestTAT,Order_Reattempt,isDelivered,isCancelled,Pending,Post_delivery_returns,Formatted_createddate,Created_to_FTAT_Diff
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-03-16 22:53:00,2024-03-16 22:54:00 UTC,2024-03-16 22:54:00 UTC,0,0,0,0,0,2024-03-16 20:53:04,119.933333
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,2024-03-12 11:45:00,2024-03-12 11:45:00 UTC,2024-03-12 11:45:00 UTC,0,0,0,0,0,2024-03-12 03:33:00,492.000000
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-02-26 20:11:00,2024-02-26 20:11:00 UTC,2024-02-26 20:11:00 UTC,0,0,0,0,0,2024-02-26 18:21:16,109.733333
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-02-27 20:49:00,2024-02-27 20:49:00 UTC,2024-02-27 21:05:00 UTC,0,0,0,0,0,2024-02-27 18:49:30,119.500000
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-03-02 19:35:00,2024-03-02 19:37:00 UTC,2024-03-02 19:37:00 UTC,0,0,0,0,0,2024-03-02 17:45:46,109.233333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,2024-03-21 12:26:00,2024-03-21 12:26:00 UTC,2024-03-21 12:26:00 UTC,0,1,0,0,0,2024-03-21 09:26:22,179.633333
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,2024-03-10 13:00:00,2024-03-10 13:00:00 UTC,2024-03-10 13:00:00 UTC,0,1,0,0,0,2024-03-09 22:44:55,855.083333
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,2024-03-16 20:26:00,2024-03-16 20:27:00 UTC,2024-03-16 20:27:00 UTC,0,1,0,0,0,2024-03-16 16:27:34,238.433333
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,2024-03-21 16:48:00,2024-03-21 16:48:00 UTC,2024-03-21 16:48:00 UTC,0,1,0,0,0,2024-03-21 13:48:22,179.633333
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,2024-03-09 17:47:00,2024-03-09 17:47:00 UTC,2024-03-09 17:47:00 UTC,0,1,0,0,0,2024-03-09 14:47:19,179.683333

In [ ]:
#Created the bucket for First TAT and Created TAT difference
df['Created_to_F_TAT_Diff_0_to_2_hrs']=np.where(df['Created_to_FTAT_Diff']<121,1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,secondTAT,latestTAT,Order_Reattempt,isDelivered,isCancelled,Pending,Post_delivery_returns,Formatted_createddate,Created_to_FTAT_Diff,Created_to_F_TAT_Diff_0_to_2_hrs
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-03-16 22:54:00 UTC,2024-03-16 22:54:00 UTC,0,0,0,0,0,2024-03-16 20:53:04,119.933333,1
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,2024-03-12 11:45:00 UTC,2024-03-12 11:45:00 UTC,0,0,0,0,0,2024-03-12 03:33:00,492.000000,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-02-26 20:11:00 UTC,2024-02-26 20:11:00 UTC,0,0,0,0,0,2024-02-26 18:21:16,109.733333,1
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-02-27 20:49:00 UTC,2024-02-27 21:05:00 UTC,0,0,0,0,0,2024-02-27 18:49:30,119.500000,1
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-03-02 19:37:00 UTC,2024-03-02 19:37:00 UTC,0,0,0,0,0,2024-03-02 17:45:46,109.233333,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,2024-03-21 12:26:00 UTC,2024-03-21 12:26:00 UTC,0,1,0,0,0,2024-03-21 09:26:22,179.633333,0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,2024-03-10 13:00:00 UTC,2024-03-10 13:00:00 UTC,0,1,0,0,0,2024-03-09 22:44:55,855.083333,0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,2024-03-16 20:27:00 UTC,2024-03-16 20:27:00 UTC,0,1,0,0,0,2024-03-16 16:27:34,238.433333,0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,2024-03-21 16:48:00 UTC,2024-03-21 16:48:00 UTC,0,1,0,0,0,2024-03-21 13:48:22,179.633333,0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,2024-03-09 17:47:00 UTC,2024-03-09 17:47:00 UTC,0,1,0,0,0,2024-03-09 14:47:19,179.683333,0

In [ ]:
#Created the bucket for First TAT and Created TAT difference
df['Created_to_F_TAT_Diff_2_to_4_hrs']=np.where((df['Created_to_FTAT_Diff']>120) & (df['Created_to_FTAT_Diff']<241),1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,latestTAT,Order_Reattempt,isDelivered,isCancelled,Pending,Post_delivery_returns,Formatted_createddate,Created_to_FTAT_Diff,Created_to_F_TAT_Diff_0_to_2_hrs,Created_to_F_TAT_Diff_2_to_4_hrs
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-03-16 22:54:00 UTC,0,0,0,0,0,2024-03-16 20:53:04,119.933333,1,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,2024-03-12 11:45:00 UTC,0,0,0,0,0,2024-03-12 03:33:00,492.000000,0,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-02-26 20:11:00 UTC,0,0,0,0,0,2024-02-26 18:21:16,109.733333,1,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-02-27 21:05:00 UTC,0,0,0,0,0,2024-02-27 18:49:30,119.500000,1,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-03-02 19:37:00 UTC,0,0,0,0,0,2024-03-02 17:45:46,109.233333,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,2024-03-21 12:26:00 UTC,0,1,0,0,0,2024-03-21 09:26:22,179.633333,0,1
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,2024-03-10 13:00:00 UTC,0,1,0,0,0,2024-03-09 22:44:55,855.083333,0,0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,2024-03-16 20:27:00 UTC,0,1,0,0,0,2024-03-16 16:27:34,238.433333,0,1
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,2024-03-21 16:48:00 UTC,0,1,0,0,0,2024-03-21 13:48:22,179.633333,0,1
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,2024-03-09 17:47:00 UTC,0,1,0,0,0,2024-03-09 14:47:19,179.683333,0,1

In [ ]:
#Created the bucket for First TAT and Created TAT difference
df['four_8hrs']=np.where((df['Created_to_FTAT_Diff']>=241) & (df['Created_to_FTAT_Diff']<=480),1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,Order_Reattempt,isDelivered,isCancelled,Pending,Post_delivery_returns,Formatted_createddate,Created_to_FTAT_Diff,Created_to_F_TAT_Diff_0_to_2_hrs,Created_to_F_TAT_Diff_2_to_4_hrs,four_8hrs
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,0,2024-03-16 20:53:04,119.933333,1,0,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,0,2024-03-12 03:33:00,492.000000,0,0,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,0,2024-02-26 18:21:16,109.733333,1,0,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,0,2024-02-27 18:49:30,119.500000,1,0,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,0,2024-03-02 17:45:46,109.233333,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,1,0,0,0,2024-03-21 09:26:22,179.633333,0,1,0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,1,0,0,0,2024-03-09 22:44:55,855.083333,0,0,0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,1,0,0,0,2024-03-16 16:27:34,238.433333,0,1,0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,1,0,0,0,2024-03-21 13:48:22,179.633333,0,1,0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,1,0,0,0,2024-03-09 14:47:19,179.683333,0,1,0

In [ ]:
#Created the bucket for First TAT and Created TAT difference
df['8_to_24hr']=np.where((df['Created_to_FTAT_Diff']>=481) & (df['Created_to_FTAT_Diff']<=1440),1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,isDelivered,isCancelled,Pending,Post_delivery_returns,Formatted_createddate,Created_to_FTAT_Diff,Created_to_F_TAT_Diff_0_to_2_hrs,Created_to_F_TAT_Diff_2_to_4_hrs,four_8hrs,8_to_24hr
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,2024-03-16 20:53:04,119.933333,1,0,0,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,2024-03-12 03:33:00,492.000000,0,0,0,1
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,2024-02-26 18:21:16,109.733333,1,0,0,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,2024-02-27 18:49:30,119.500000,1,0,0,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,2024-03-02 17:45:46,109.233333,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1,0,0,0,2024-03-21 09:26:22,179.633333,0,1,0,0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,1,0,0,0,2024-03-09 22:44:55,855.083333,0,0,0,1
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,1,0,0,0,2024-03-16 16:27:34,238.433333,0,1,0,0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,1,0,0,0,2024-03-21 13:48:22,179.633333,0,1,0,0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1,0,0,0,2024-03-09 14:47:19,179.683333,0,1,0,0

In [ ]:
#Created the bucket for First TAT and Created TAT difference
df['twentyfour_48hrs']=np.where((df['Created_to_FTAT_Diff']>=1441) & (df['Created_to_FTAT_Diff']<=2880),1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,isCancelled,Pending,Post_delivery_returns,Formatted_createddate,Created_to_FTAT_Diff,Created_to_F_TAT_Diff_0_to_2_hrs,Created_to_F_TAT_Diff_2_to_4_hrs,four_8hrs,8_to_24hr,twentyfour_48hrs
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,2024-03-16 20:53:04,119.933333,1,0,0,0,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,0,0,2024-03-12 03:33:00,492.000000,0,0,0,1,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,2024-02-26 18:21:16,109.733333,1,0,0,0,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,2024-02-27 18:49:30,119.500000,1,0,0,0,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,2024-03-02 17:45:46,109.233333,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,0,2024-03-21 09:26:22,179.633333,0,1,0,0,0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,0,0,2024-03-09 22:44:55,855.083333,0,0,0,1,0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,0,0,2024-03-16 16:27:34,238.433333,0,1,0,0,0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,0,0,2024-03-21 13:48:22,179.633333,0,1,0,0,0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,0,2024-03-09 14:47:19,179.683333,0,1,0,0,0

In [ ]:
df['grater_48hrs']=np.where(df['Created_to_FTAT_Diff']>2880,1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,Store_Pushed,Billed_time_min,DSP_Allocation_In_Min,pickup_in_minuts,Rider_delivery_in_Min,O2D_in_min,Verified_in_Min,Return_Cancelled,post_billing,grater_48hrs
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,0.250000,0,0,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1,3.716667,0.200000,8.466667,4.733333,26.983333,NaN,0,0,0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,1,11.433333,0.183333,10.416667,3.733333,26.866667,0.266667,0,0,0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,1,1.433333,5.966667,8.616667,1.733333,33.650000,NaN,0,0,0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,1,58.100000,0.166667,3.783333,1.516667,16.783333,NaN,0,0,0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1,2.866667,0.133333,4.000000,1.483333,17.633333,NaN,0,0,0

In [ ]:
#Created to track the Orders whose terminal status is delivered and cancelled after delivery
df['NetDelivery']=np.where (df['delivered'].notna(),1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,Pending,Post_delivery_returns,Formatted_createddate,Created_to_FTAT_Diff,Created_to_F_TAT_Diff_0_to_2_hrs,Created_to_F_TAT_Diff_2_to_4_hrs,four_8hrs,8_to_24hr,twentyfour_48hrs,NetDelivery
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,2024-03-16 20:53:04,119.933333,1,0,0,0,0,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,0,2024-03-12 03:33:00,492.000000,0,0,0,1,0,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,2024-02-26 18:21:16,109.733333,1,0,0,0,0,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,2024-02-27 18:49:30,119.500000,1,0,0,0,0,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,2024-03-02 17:45:46,109.233333,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,2024-03-21 09:26:22,179.633333,0,1,0,0,0,1
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,0,2024-03-09 22:44:55,855.083333,0,0,0,1,0,1
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,0,2024-03-16 16:27:34,238.433333,0,1,0,0,0,1
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,0,2024-03-21 13:48:22,179.633333,0,1,0,0,0,1
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,2024-03-09 14:47:19,179.683333,0,1,0,0,0,1

In [ ]:
df['delivered']=pd.to_datetime(df['delivered']).dt.strftime('%Y-%m-%d %H:%M:%S')

df['firstTAT']=pd.to_datetime(df['firstTAT']).dt.strftime('%Y-%m-%d %H:%M:%S')

<ipython-input-59-94fe80dc0249>:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['delivered']=pd.to_datetime(df['delivered']).dt.strftime('%Y-%m-%d %H:%M:%S')

In [ ]:
#Created to track First TAT Adherence
df['First_SLA_Adherence'] = np.where(df['NetDelivery'] == 1, np.where(df['delivered'] <= df['firstTAT'], 1,0),np.nan)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,Post_delivery_returns,Formatted_createddate,Created_to_FTAT_Diff,Created_to_F_TAT_Diff_0_to_2_hrs,Created_to_F_TAT_Diff_2_to_4_hrs,four_8hrs,8_to_24hr,twentyfour_48hrs,NetDelivery,First_SLA_Adherence
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,2024-03-16 20:53:04,119.933333,1,0,0,0,0,0,NaN
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,2024-03-12 03:33:00,492.000000,0,0,0,1,0,0,NaN
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,2024-02-26 18:21:16,109.733333,1,0,0,0,0,0,NaN
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,2024-02-27 18:49:30,119.500000,1,0,0,0,0,0,NaN
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,2024-03-02 17:45:46,109.233333,1,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,2024-03-21 09:26:22,179.633333,0,1,0,0,0,1,1.0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,2024-03-09 22:44:55,855.083333,0,0,0,1,0,1,0.0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,2024-03-16 16:27:34,238.433333,0,1,0,0,0,1,1.0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,2024-03-21 13:48:22,179.633333,0,1,0,0,0,1,1.0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,2024-03-09 14:47:19,179.683333,0,1,0,0,0,1,0.0

In [ ]:

df['secondTAT']=pd.to_datetime(df['secondTAT']).dt.strftime('%Y-%m-%d %H:%M:%S')
df['latestTAT']=pd.to_datetime(df['latestTAT']).dt.strftime('%Y-%m-%d %H:%M:%S')

In [ ]:
##Created to track Second TAT Adherence
df['Second_SLA_Adherence'] = np.where(df['NetDelivery'] == 1, np.where(df['delivered'] <= df['secondTAT'], 1,0),np.nan)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,Formatted_createddate,Created_to_FTAT_Diff,Created_to_F_TAT_Diff_0_to_2_hrs,Created_to_F_TAT_Diff_2_to_4_hrs,four_8hrs,8_to_24hr,twentyfour_48hrs,NetDelivery,First_SLA_Adherence,Second_SLA_Adherence
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-03-16 20:53:04,119.933333,1,0,0,0,0,0,NaN,NaN
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,2024-03-12 03:33:00,492.000000,0,0,0,1,0,0,NaN,NaN
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-02-26 18:21:16,109.733333,1,0,0,0,0,0,NaN,NaN
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-02-27 18:49:30,119.500000,1,0,0,0,0,0,NaN,NaN
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-03-02 17:45:46,109.233333,1,0,0,0,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,2024-03-21 09:26:22,179.633333,0,1,0,0,0,1,1.0,0.0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,2024-03-09 22:44:55,855.083333,0,0,0,1,0,1,0.0,1.0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,2024-03-16 16:27:34,238.433333,0,1,0,0,0,1,1.0,1.0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,2024-03-21 13:48:22,179.633333,0,1,0,0,0,1,1.0,0.0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,2024-03-09 14:47:19,179.683333,0,1,0,0,0,1,0.0,1.0

In [ ]:
##Created to track Latest TAT Adherence
df['latest_SLA_Adherence'] = np.where(df['NetDelivery'] == 1, np.where(df['delivered'] <= df['latestTAT'], 1,0),np.nan)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,Created_to_FTAT_Diff,Created_to_F_TAT_Diff_0_to_2_hrs,Created_to_F_TAT_Diff_2_to_4_hrs,four_8hrs,8_to_24hr,twentyfour_48hrs,NetDelivery,First_SLA_Adherence,Second_SLA_Adherence,latest_SLA_Adherence
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,119.933333,1,0,0,0,0,0,NaN,NaN,NaN
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,492.000000,0,0,0,1,0,0,NaN,NaN,NaN
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,109.733333,1,0,0,0,0,0,NaN,NaN,NaN
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,119.500000,1,0,0,0,0,0,NaN,NaN,NaN
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,109.233333,1,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,179.633333,0,1,0,0,0,1,1.0,0.0,0.0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,855.083333,0,0,0,1,0,1,0.0,1.0,1.0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,238.433333,0,1,0,0,0,1,1.0,1.0,1.0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,179.633333,0,1,0,0,0,1,1.0,0.0,0.0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,179.683333,0,1,0,0,0,1,0.0,1.0,1.0

In [ ]:
#Created to track total orders count
df['count']=np.where(df['orderid'].notna(),1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,Created_to_F_TAT_Diff_0_to_2_hrs,Created_to_F_TAT_Diff_2_to_4_hrs,four_8hrs,8_to_24hr,twentyfour_48hrs,NetDelivery,First_SLA_Adherence,Second_SLA_Adherence,latest_SLA_Adherence,count
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0,0,0,0,0,NaN,NaN,NaN,1
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,0,0,NaN,NaN,NaN,1
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0,0,0,0,0,NaN,NaN,NaN,1
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0,0,0,0,0,NaN,NaN,NaN,1
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0,0,0,0,0,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,1,0,0,0,1,1.0,0.0,0.0,1
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,0,0,1,0,1,0.0,1.0,1.0,1
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,1,0,0,0,1,1.0,1.0,1.0,1
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,1,0,0,0,1,1.0,0.0,0.0,1
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,1,0,0,0,1,0.0,1.0,1.0,1

In [ ]:
#Cretaed to track where the actual pendency is
df['prebill']=np.where((df['pendencyFlag']=='pending') & (df['pendencyType']=='pre-Billing'),1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,Created_to_F_TAT_Diff_2_to_4_hrs,four_8hrs,8_to_24hr,twentyfour_48hrs,NetDelivery,First_SLA_Adherence,Second_SLA_Adherence,latest_SLA_Adherence,count,prebill
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,0,NaN,NaN,NaN,1,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,0,1,0,0,NaN,NaN,NaN,1,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,0,NaN,NaN,NaN,1,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,0,NaN,NaN,NaN,1,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,0,NaN,NaN,NaN,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1,0,0,0,1,1.0,0.0,0.0,1,0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,0,1,0,1,0.0,1.0,1.0,1,0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,1,0,0,0,1,1.0,1.0,1.0,1,0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,1,0,0,0,1,1.0,0.0,0.0,1,0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1,0,0,0,1,0.0,1.0,1.0,1,0

In [ ]:
#Cretaed to track where the actual pendency is
df['pre_store_pending']=np.where((df['pendencyFlag']=='pending') &( df['pendencyType']=='pre-Verification'),1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,four_8hrs,8_to_24hr,twentyfour_48hrs,NetDelivery,First_SLA_Adherence,Second_SLA_Adherence,latest_SLA_Adherence,count,prebill,pre_store_pending
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,NaN,NaN,NaN,1,0,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,1,0,0,NaN,NaN,NaN,1,0,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,NaN,NaN,NaN,1,0,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,NaN,NaN,NaN,1,0,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,NaN,NaN,NaN,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,0,1,1.0,0.0,0.0,1,0,0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,1,0,1,0.0,1.0,1.0,1,0,0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,0,0,1,1.0,1.0,1.0,1,0,0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,0,0,1,1.0,0.0,0.0,1,0,0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,0,1,0.0,1.0,1.0,1,0,0

In [ ]:
#Cretaed to track where the actual pendency is
df['postShip_Pending']=np.where((df['pendencyFlag']=='pending') &( df['pendencyType']=='in-Transit'),1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,8_to_24hr,twentyfour_48hrs,NetDelivery,First_SLA_Adherence,Second_SLA_Adherence,latest_SLA_Adherence,count,prebill,pre_store_pending,postShip_Pending
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,NaN,NaN,NaN,1,0,0,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,1,0,0,NaN,NaN,NaN,1,0,0,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,NaN,NaN,NaN,1,0,0,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,NaN,NaN,NaN,1,0,0,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,NaN,NaN,NaN,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,1,1.0,0.0,0.0,1,0,0,0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,1,0,1,0.0,1.0,1.0,1,0,0,0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,0,1,1.0,1.0,1.0,1,0,0,0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,0,1,1.0,0.0,0.0,1,0,0,0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,1,0.0,1.0,1.0,1,0,0,0

In [ ]:
df['post_billing']=np.where((df['pendencyFlag']=='Attempted') &( df['pendencyType']=='post-Billing'),1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,DSP_Assigned,Store_Pushed,Billed_time_min,DSP_Allocation_In_Min,pickup_in_minuts,Rider_delivery_in_Min,O2D_in_min,Verified_in_Min,Return_Cancelled,post_billing
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,1,NaN,NaN,NaN,NaN,NaN,0.250000,0,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,1,NaN,NaN,NaN,NaN,NaN,NaN,0,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,1,NaN,NaN,NaN,NaN,NaN,NaN,0,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,1,NaN,NaN,NaN,NaN,NaN,NaN,0,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,1,NaN,NaN,NaN,NaN,NaN,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1,1,3.716667,0.200000,8.466667,4.733333,26.983333,NaN,0,0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,1,1,11.433333,0.183333,10.416667,3.733333,26.866667,0.266667,0,0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,1,1,1.433333,5.966667,8.616667,1.733333,33.650000,NaN,0,0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,1,1,58.100000,0.166667,3.783333,1.516667,16.783333,NaN,0,0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1,1,2.866667,0.133333,4.000000,1.483333,17.633333,NaN,0,0

In [ ]:
#Cretaed to track where the actual pendency is
df['DSP_Assigned']=np.where(df['forwardDSP'].notna(),1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,twentyfour_48hrs,NetDelivery,First_SLA_Adherence,Second_SLA_Adherence,latest_SLA_Adherence,count,prebill,pre_store_pending,postShip_Pending,DSP_Assigned
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,NaN,NaN,NaN,1,0,0,0,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,0,NaN,NaN,NaN,1,0,0,0,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,NaN,NaN,NaN,1,0,0,0,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,NaN,NaN,NaN,1,0,0,0,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,NaN,NaN,NaN,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,1,1.0,0.0,0.0,1,0,0,0,1
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,1,0.0,1.0,1.0,1,0,0,0,1
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,1,1.0,1.0,1.0,1,0,0,0,1
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,1,1.0,0.0,0.0,1,0,0,0,1
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,1,0.0,1.0,1.0,1,0,0,0,1

In [ ]:
#Cretaed to track whether the order is landed on store or not
df['Store_Pushed']=np.where(df['SHOPID'].notna(),1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,NetDelivery,First_SLA_Adherence,Second_SLA_Adherence,latest_SLA_Adherence,count,prebill,pre_store_pending,postShip_Pending,DSP_Assigned,Store_Pushed
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,NaN,NaN,NaN,1,0,0,0,0,1
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,NaN,NaN,NaN,1,0,0,0,0,1
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,NaN,NaN,NaN,1,0,0,0,0,1
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,NaN,NaN,NaN,1,0,0,0,0,1
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,NaN,NaN,NaN,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1,1.0,0.0,0.0,1,0,0,0,1,1
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,1,0.0,1.0,1.0,1,0,0,0,1,1
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,1,1.0,1.0,1.0,1,0,0,0,1,1
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,1,1.0,0.0,0.0,1,0,0,0,1,1
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1,0.0,1.0,1.0,1,0,0,0,1,1

In [ ]:
df['last_shc']=pd.to_datetime(df['last_shc'])
df['billed']=pd.to_datetime(df['billed'])

<ipython-input-28-e51d4255e9c9>:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['last_shc']=pd.to_datetime(df['last_shc'])
<ipython-input-28-e51d4255e9c9>:2: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['billed']=pd.to_datetime(df['billed'])

In [ ]:
#Cretaed to track how much time order took for billing once it landed on store
df['Billed_time_min']= np.where(df['billed'].notna() & df['last_shc'].notna(),
np.maximum((df['billed'] - df['last_shc']).dt.total_seconds() / 60, 0),np.nan)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,First_SLA_Adherence,Second_SLA_Adherence,latest_SLA_Adherence,count,prebill,pre_store_pending,postShip_Pending,DSP_Assigned,Store_Pushed,Billed_time_min
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,1,0,0,0,0,1,NaN
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,1,0,0,0,0,1,NaN
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,1,0,0,0,0,1,NaN
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,1,0,0,0,0,1,NaN
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,1,0,0,0,0,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1.0,0.0,0.0,1,0,0,0,1,1,3.716667
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0.0,1.0,1.0,1,0,0,0,1,1,11.433333
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,1.0,1.0,1.0,1,0,0,0,1,1,1.433333
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,1.0,0.0,0.0,1,0,0,0,1,1,58.100000
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0.0,1.0,1.0,1,0,0,0,1,1,2.866667

In [ ]:
df['firstpacked']=pd.to_datetime(df['firstpacked'])
df['billed']=pd.to_datetime(df['billed'])

<ipython-input-30-bbbc09c7d54c>:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['firstpacked']=pd.to_datetime(df['firstpacked'])

In [ ]:
#Cretaed to track how much time order took for rider assignment
df['DSP_Allocation_In_Min'] = np.where(df['billed'].notna() & df['firstpacked'].notna(),
np.maximum((df['firstpacked'] - df['billed']).dt.total_seconds() / 60, 0),np.nan)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,Second_SLA_Adherence,latest_SLA_Adherence,count,prebill,pre_store_pending,postShip_Pending,DSP_Assigned,Store_Pushed,Billed_time_min,DSP_Allocation_In_Min
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,1,0,0,0,0,1,NaN,NaN
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,1,0,0,0,0,1,NaN,NaN
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,1,0,0,0,0,1,NaN,NaN
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,1,0,0,0,0,1,NaN,NaN
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,1,0,0,0,0,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0.0,0.0,1,0,0,0,1,1,3.716667,0.200000
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,1.0,1.0,1,0,0,0,1,1,11.433333,0.183333
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,1.0,1.0,1,0,0,0,1,1,1.433333,5.966667
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0.0,0.0,1,0,0,0,1,1,58.100000,0.166667
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1.0,1.0,1,0,0,0,1,1,2.866667,0.133333

In [ ]:
df['firstshipped']=pd.to_datetime(df['firstshipped'])
df['first_rts']=pd.to_datetime(df['first_rts'])

<ipython-input-32-fa68aba82a8a>:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['firstshipped']=pd.to_datetime(df['firstshipped'])
<ipython-input-32-fa68aba82a8a>:2: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['first_rts']=pd.to_datetime(df['first_rts'])

In [ ]:
#Cretaed to track how much time order took to get picked up by rider
df['pickup_in_minuts'] = np.where(df['firstshipped'].notna() & df['first_rts'].notna(),
np.maximum((df['firstshipped'] - df['first_rts']).dt.total_seconds() / 60, 0),np.nan)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,latest_SLA_Adherence,count,prebill,pre_store_pending,postShip_Pending,DSP_Assigned,Store_Pushed,Billed_time_min,DSP_Allocation_In_Min,pickup_in_minuts
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,1,0,0,0,0,1,NaN,NaN,NaN
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,NaN,1,0,0,0,0,1,NaN,NaN,NaN
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,1,0,0,0,0,1,NaN,NaN,NaN
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,1,0,0,0,0,1,NaN,NaN,NaN
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,1,0,0,0,0,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0.0,1,0,0,0,1,1,3.716667,0.200000,8.466667
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,1.0,1,0,0,0,1,1,11.433333,0.183333,10.416667
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,1.0,1,0,0,0,1,1,1.433333,5.966667,8.616667
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0.0,1,0,0,0,1,1,58.100000,0.166667,3.783333
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1.0,1,0,0,0,1,1,2.866667,0.133333,4.000000

In [ ]:
df['delivered']=pd.to_datetime(df['delivered'])
df['lastshipped']=pd.to_datetime(df['lastshipped'])

<ipython-input-34-ecd6f88f98ce>:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['delivered']=pd.to_datetime(df['delivered'])
<ipython-input-34-ecd6f88f98ce>:2: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['lastshipped']=pd.to_datetime(df['lastshipped'])

In [ ]:
#Cretaed to track how much time rider took to deliver the order once it gets in hand
df['Rider_delivery_in_Min']=np.where(df['delivered'].notna() & df['lastshipped'].notna(),
np.maximum((df['delivered'] - df['lastshipped']).dt.total_seconds() / 60, 0),np.nan)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,count,prebill,pre_store_pending,postShip_Pending,DSP_Assigned,Store_Pushed,Billed_time_min,DSP_Allocation_In_Min,pickup_in_minuts,Rider_delivery_in_Min
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0,0,0,0,1,NaN,NaN,NaN,NaN
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,1,0,0,0,0,1,NaN,NaN,NaN,NaN
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0,0,0,0,1,NaN,NaN,NaN,NaN
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0,0,0,0,1,NaN,NaN,NaN,NaN
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0,0,0,0,1,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1,0,0,0,1,1,3.716667,0.200000,8.466667,14.200000
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,1,0,0,0,1,1,11.433333,0.183333,10.416667,8.666667
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,1,0,0,0,1,1,1.433333,5.966667,8.616667,14.250000
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,1,0,0,0,1,1,58.100000,0.166667,3.783333,12.566667
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1,0,0,0,1,1,2.866667,0.133333,4.000000,8.516667

In [ ]:
#Cretaed to track how much time order took to get delivered from getting billed to delivered
df['O2D_in_min']=np.where(df['delivered'].notna() & df['billed'].notna(),
np.maximum((df['delivered'] - df['billed']).dt.total_seconds() / 60, 0),np.nan)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,prebill,pre_store_pending,postShip_Pending,DSP_Assigned,Store_Pushed,Billed_time_min,DSP_Allocation_In_Min,pickup_in_minuts,Rider_delivery_in_Min,O2D_in_min
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,0,1,1,3.716667,0.200000,8.466667,14.200000,26.983333
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,0,0,1,1,11.433333,0.183333,10.416667,8.666667,26.866667
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,0,0,1,1,1.433333,5.966667,8.616667,14.250000,33.650000
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,0,0,1,1,58.100000,0.166667,3.783333,12.566667,16.783333
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,0,1,1,2.866667,0.133333,4.000000,8.516667,17.633333

In [ ]:
df['rider_reached_store']=pd.to_datetime(df['rider_reached_store'])
df['first_ofd']=pd.to_datetime(df['first_ofd'])

<ipython-input-37-9ca76799de67>:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['rider_reached_store']=pd.to_datetime(df['rider_reached_store'])
<ipython-input-37-9ca76799de67>:2: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['first_ofd']=pd.to_datetime(df['first_ofd'])

In [ ]:
#Cretaed to track how much time rider took to reach the store
df['Rider_delivery_in_Min']=np.where(df['rider_reached_store'].notna() & df['first_ofd'].notna(),
np.maximum((df['first_ofd'] - df['rider_reached_store']).dt.total_seconds() / 60, 0),np.nan)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,prebill,pre_store_pending,postShip_Pending,DSP_Assigned,Store_Pushed,Billed_time_min,DSP_Allocation_In_Min,pickup_in_minuts,Rider_delivery_in_Min,O2D_in_min
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,0,1,1,3.716667,0.200000,8.466667,4.733333,26.983333
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,0,0,1,1,11.433333,0.183333,10.416667,3.733333,26.866667
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,0,0,1,1,1.433333,5.966667,8.616667,1.733333,33.650000
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,0,0,1,1,58.100000,0.166667,3.783333,1.516667,16.783333
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,0,1,1,2.866667,0.133333,4.000000,1.483333,17.633333

In [ ]:
df['verified']=pd.to_datetime(df['verified'])
df['booked']=pd.to_datetime(df['booked'])

<ipython-input-40-b1f76063b405>:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['verified']=pd.to_datetime(df['verified'])
<ipython-input-40-b1f76063b405>:2: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['booked']=pd.to_datetime(df['booked'])

In [ ]:
#Time taken for verification
df['Verified_in_Min']=np.where(df['verified'].notna() & df['booked'].notna(),
np.maximum((df['verified'] - df['booked']).dt.total_seconds() / 60, 0),np.nan)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,pre_store_pending,postShip_Pending,DSP_Assigned,Store_Pushed,Billed_time_min,DSP_Allocation_In_Min,pickup_in_minuts,Rider_delivery_in_Min,O2D_in_min,Verified_in_Min
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,NaN,NaN,NaN,NaN,NaN,0.250000
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,1,1,3.716667,0.200000,8.466667,4.733333,26.983333,NaN
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,0,1,1,11.433333,0.183333,10.416667,3.733333,26.866667,0.266667
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,0,1,1,1.433333,5.966667,8.616667,1.733333,33.650000,NaN
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,0,1,1,58.100000,0.166667,3.783333,1.516667,16.783333,NaN
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,1,1,2.866667,0.133333,4.000000,1.483333,17.633333,NaN

In [ ]:
df['Return_Cancelled']=np.where(df['LATESTORDERSTATUS']=='RETURN_REQUEST_CANCELLED',1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,postShip_Pending,DSP_Assigned,Store_Pushed,Billed_time_min,DSP_Allocation_In_Min,pickup_in_minuts,Rider_delivery_in_Min,O2D_in_min,Verified_in_Min,Return_Cancelled
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,1,NaN,NaN,NaN,NaN,NaN,0.250000,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,1,1,3.716667,0.200000,8.466667,4.733333,26.983333,NaN,0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,1,1,11.433333,0.183333,10.416667,3.733333,26.866667,0.266667,0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,1,1,1.433333,5.966667,8.616667,1.733333,33.650000,NaN,0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,1,1,58.100000,0.166667,3.783333,1.516667,16.783333,NaN,0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,1,1,2.866667,0.133333,4.000000,1.483333,17.633333,NaN,0

In [ ]:
df.columns

Index(['orderid', 'cust_pin', 'SHOPID', 'store_city', 'customer_city_bucket',
       'store_type', 'City_Bucket', 'LATESTORDERSTATUS', 'systemDSP',
       'forwardDSP', 'pendencyFlag', 'pendencyType', 'orderDateXls',
       'firstTatDate', 'secondTatDate', 'created_ts_IST', 'booked',
       'rider_reached_store', 'verified', 'first_shc', 'last_shc', 'billed',
       'firstpacked', 'lastpacked', 'first_rts', 'last_rts', 'firstshipped',
       'lastshipped', 'first_ofd', 'last_ofd', 'first_attempted',
       'rider_reached_customer_gate', 'delivery_attempted', 'delivered',
       'cancelled', 'return_pending', 'return_requested', 'firstTAT',
       'secondTAT', 'latestTAT', 'Order_Reattempt', 'isDelivered',
       'isCancelled', 'Pending', 'Post_delivery_returns',
       'Formatted_createddate', 'Created_to_FTAT_Diff',
       'Created_to_F_TAT_Diff_0_to_2_hrs', 'Created_to_F_TAT_Diff_2_to_4_hrs',
       'four_8hrs', '8_to_24hr', 'twentyfour_48hrs', 'NetDelivery',
       'First_SLA_Adherence', 'Second_SLA_Adherence', 'latest_SLA_Adherence',
       'count', 'prebill', 'pre_store_pending', 'postShip_Pending',
       'DSP_Assigned', 'Store_Pushed', 'Billed_time_min',
       'DSP_Allocation_In_Min', 'pickup_in_minuts', 'Rider_delivery_in_Min',
       'O2D_in_min', 'Verified_in_Min', 'Return_Cancelled', 'post_billing',
       'grater_48hrs'],
      dtype='object')

In [ ]:
import os

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
file_path = '/content/drive/MyDrive/Case_Study_on_Delivery_Performance_Optimization.ipynb.xlsx'

# Save the file to Google Drive
df.to_excel(file_path, index=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df2=df

In [ ]:
group=df.groupby('City_Bucket')['NetDelivery'].sum()
group

City_Bucket
Bangalore                3258
Chennai                  1949
Delhi-NCR                4050
East - KOL Ops            361
Expansion                2136
Hyderabad                3009
Karaka - Other Cities     173
Kolkata                  2307
Mumbai                    428
South - CHN Ops           356
South - Tier 2            681
Name: NetDelivery, dtype: int64

In [ ]:
group=df.groupby(['City_Bucket','forwardDSP'])['NetDelivery'].sum()
group

City_Bucket     forwardDSP
Bangalore       AAAA            70
                BBBB           254
                CCCC             9
                DDDD          2154
                EEEE           156
                              ...
South - Tier 2  CCCC           199
                DDDD           100
                EEEE            38
                FFFF           238
                GGGG             5
Name: NetDelivery, Length: 91, dtype: int64

In [ ]:
group=df.groupby('City_Bucket').agg(
    NetDelivery= ('NetDelivery','sum'),
    isDelivered= ('isDelivered', 'sum'),
    isCancelled =('isCancelled', 'sum')

    )
group

                       NetDelivery  isDelivered  isCancelled
City_Bucket
Bangalore                     3258         3230          165
Chennai                       1949         1941           67
Delhi-NCR                     4050         4024          280
East - KOL Ops                 361          358           32
Expansion                     2136         2099          182
Hyderabad                     3009         2966          148
Karaka - Other Cities          173          168            9
Kolkata                       2307         2299          103
Mumbai                         428          428           30
South - CHN Ops                356          350           22
South - Tier 2                 681          670           57

In [ ]:
pivot=df.pivot_table(index='City_Bucket',columns='forwardDSP',values=['NetDelivery','isDelivered','isCancelled'],
          aggfunc={'NetDelivery':'sum','isDelivered':'sum','isCancelled':'sum'},



          )
pivot

                      NetDelivery                                           \
forwardDSP                   AAAA   BBBB   CCCC    DDDD   EEEE   FFFF GGGG
City_Bucket
Bangalore                    70.0  254.0    9.0  2154.0  156.0  538.0  7.0
Chennai                     174.0  780.0   69.0   898.0   14.0    9.0  NaN
Delhi-NCR                   199.0  232.0    7.0  2872.0  185.0  511.0  9.0
East - KOL Ops               60.0   16.0    NaN   180.0    6.0   97.0  1.0
Expansion                   190.0  164.0  685.0   355.0  110.0  607.0  4.0
Hyderabad                   218.0  343.0   47.0  2000.0   47.0  309.0  6.0
Karaka - Other Cities        11.0   37.0   51.0    26.0   13.0   31.0  NaN
Kolkata                     103.0  226.0  136.0  1694.0   68.0   50.0  6.0
Mumbai                       29.0   13.0   68.0   300.0   18.0    NaN  NaN
South - CHN Ops              49.0   76.0   49.0    41.0   87.0   44.0  NaN
South - Tier 2               51.0   50.0  199.0   100.0   38.0  238.0  5.0

                                        ... isDelivered                        \
forwardDSP             HHHH  IIII JJJJ  ...        FFFF GGGG  HHHH  IIII JJJJ
City_Bucket                             ...
Bangalore              20.0  43.0  6.0  ...       539.0  7.0  20.0  44.0  6.0
Chennai                 2.0   3.0  NaN  ...         9.0  NaN   2.0   3.0  NaN
Delhi-NCR              34.0   NaN  NaN  ...       512.0  9.0  33.0   NaN  NaN
East - KOL Ops          NaN   NaN  NaN  ...        95.0  1.0   NaN   NaN  NaN
Expansion               4.0   NaN  NaN  ...       595.0  4.0   6.0   NaN  NaN
Hyderabad              30.0   4.0  NaN  ...       301.0  5.0  29.0   4.0  NaN
Karaka - Other Cities   NaN   4.0  NaN  ...        30.0  NaN   NaN   4.0  NaN
Kolkata                 8.0   NaN  NaN  ...        50.0  7.0   8.0   NaN  NaN
Mumbai                  NaN   NaN  NaN  ...         NaN  NaN   NaN   NaN  NaN
South - CHN Ops         NaN   9.0  NaN  ...        44.0  NaN   NaN   9.0  NaN
South - Tier 2          NaN   NaN  NaN  ...       234.0  5.0   NaN   NaN  NaN


forwardDSP            KKKK  LLLL  MMMM NNNN OOOO
City_Bucket
Bangalore              0.0   NaN   NaN  NaN  NaN
Chennai                NaN   NaN   NaN  NaN  NaN
Delhi-NCR              NaN   NaN   1.0  0.0  NaN
East - KOL Ops         1.0   NaN   NaN  NaN  NaN
Expansion              NaN  16.0   NaN  NaN  NaN
Hyderabad              NaN   NaN   5.0  NaN  NaN
Karaka - Other Cities  NaN   NaN   NaN  NaN  NaN
Kolkata                NaN   NaN  16.0  NaN  NaN
Mumbai                 NaN   NaN   NaN  NaN  NaN
South - CHN Ops        NaN   NaN   NaN  NaN  1.0
South - Tier 2         NaN   NaN   NaN  NaN  NaN

[11 rows x 45 columns]